### ISSUE TITLE
Finding the imports?

### ISSUE THREAD

**Issue by bartonhammond** [bitbldr/sprocket_starter#1]
First - thanks for making this!  

In the tutorial there is this definition:
`pub fn product_card(product: Product, actions: Option(List(Element))) {`

How do I find the required imports?  What is Option, List, Element?  

I'm using VS Code. 

Again thanks!

**Comment by eliknebel** [comment]
Hi thanks for the feedback! Some of these types are from the gleam stdlib such as `Option` and `List`. `Element` is a sprocket type that specifies what gets returned by a component.

The examples in the tutorial are intentionally sparse to try and focus on the important bits being explained. They also build off of previous code examples so if you are following along, it will require a bit of compiling code snippets together to actually get a functioning project. I do agree on the components page it might be a little too sparse though, so I've updated some of the code examples to show the imports for better context.

All of the actual working components can also be found in the sprocket docs repository https://github.com/bitbldr/sprocket_docs/tree/master/src/docs/components
